apiVersion: v1
kind: Service
metadata:
  name: jobs-worker-metrics
  namespace: team-alpha
  labels:
    app: jobs-worker
spec:
  selector:
    app: jobs-worker
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
