apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-alpha-jobs-worker
  namespace: platform-system
spec:
  project: default
  source:
    repoURL: https://github.com/thunderbolt-ops/ecps.git
    targetRevision: feat/billing-platform-app
    path: apps/team-alpha/jobs-worker/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: team-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
