apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-alpha-billing-api
  namespace: platform-system
  labels:
    app.kubernetes.io/part-of: ecps
    ecps/team: team-alpha
spec:
  project: default
  source:
    repoURL: https://github.com/thunderbolt-ops/ecps.git   
    targetRevision: feat/billing-platform-app                                   # or your branch
    path: apps/team-alpha/billing-api/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: team-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
