apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: team-alpha
  labels:
    app: jobs-api
    team: team-alpha
spec:
  selector:
    app: jobs-api
  ports:
    - name: http
      port: 80
      targetPort: 8000

