apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: billing-api
  namespace: team-alpha
  labels:
    app: billing-api
    team: team-alpha
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: billing-api
  namespaceSelector:
    matchNames:
      - team-alpha
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
