apiVersion: v1
kind: Service
metadata:
  name: reporting-api
  namespace: team-alpha
  labels:
    app: reporting-api
    team: team-alpha
spec:
  type: ClusterIP
  selector:
    app: reporting-api
  ports:
    - name: http
      port: 80
      targetPort: http
